---
- name: Fetch kubeconfig from master
  hosts: controlplane
  become: yes
  tasks:
    - name: Copy kubeconfig to workstation
      fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: "{{ playbook_dir }}/../kubeconfig"
        flat: yes