roles:
  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker
    version: 7.2.0
  - name: geerlingguy.kubernetes
    src: https://github.com/geerlingguy/ansible-role-kubernetes
    version: 7.1.1