---
# Install Kubernetes tools on workstation

- name: Download kubectl
  get_url:
    url: https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Download Helm
  get_url:
    url: https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz

- name: Extract Helm
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/linux-amd64/helm

- name: Move Helm binary to /usr/local/bin
  command: mv /usr/local/bin/linux-amd64/helm /usr/local/bin/helm
  args:
    creates: /usr/local/bin/helm

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
