---
# Install RKE2 server/agent

- name: Download RKE2 installer
  shell: curl -sfL https://get.rke2.io | sh -

- name: Enable RKE2 service (server)
  systemd:
    name: rke2-server
    enabled: yes
    state: started
  when: "'controlplane' in group_names"

- name: Enable RKE2 service (agent)
  systemd:
    name: rke2-agent
    enabled: yes
    state: started
  when: "'workers' in group_names"

- name: Copy server config template
  template:
    src: rke2_server_config.j2
    dest: /etc/rancher/rke2/config.yaml
  when: "'controlplane' in group_names"

- name: Copy agent config template
  template:
    src: rke2_agent_config.j2
    dest: /etc/rancher/rke2/config.yaml
  when: "'workers' in group_names"
